### ISSUE TITLE
At least one meeting time!?

### ISSUE THREAD

**Issue by di-huang** [dhuang12138/CS2820#12]
I worked all of these in current production file last night, so I was so tired that I was not able to attend the class today. I'm sorry to miss that opportunity. Therefore, we can arrange a meeting tonight or tomorrow and discuss all about our final production and what we're gonna do at the demo day.

**Comment by josephLeiferman** [comment]
Tomorrow sometime after 5 works for me.

**Comment by josephLeiferman** [comment]
Di, I have fixed the problem of shelves traveling through each other. Instead of calling getRoute() when a robot has already picked up a shelf, all Wei Gui needs to do implement the new method getRouteWithShelf()

**Comment by di-huang** [comment]
So, today is a meeting day, right? @weigui @josephLeiferman @Bryant-Xu @charlesc3929 @NickEBarnes

**Comment by ghost** [comment]
Yes today after 5 works for me as well. I'm assuming in the comp lab in Maclean?

**Comment by NickEBarnes** [comment]
It's gonna be difficult for me to meet today but let me know what time you guys are thinking

**Comment by weigui** [comment]
I see

**Comment by josephLeiferman** [comment]
I can meet at 5:15 in Maclean in computer lab if that works for the majority of us.

**Comment by NickEBarnes** [comment]
I should be able to do that
________________________________

**Comment by ghost** [comment]
I can also

**Comment by josephLeiferman** [comment]
Are we meeting than at maclean?

**Comment by NickEBarnes** [comment]
Yes. Me and Charles are up top
________________________________

**Comment by weigui** [comment]
looks like I can't be there

**Comment by di-huang** [comment]
I'll be there in 20 mins

**Comment by josephLeiferman** [comment]
Hey Di, will you be able to make it to Maclean tonight three of us are here now.

**Comment by Bryant-Xu** [comment]
i have a Rhetoric class this evening from 6 to 9. i may not be there until 9PM.

**Comment by Bryant-Xu** [comment]
i may talk to Di huang later, just let me know what happened during group meeting.

**Comment by weigui** [comment]
I'm now modifying Visualizer, maybe just committing it once, please be aware not to make any conflicts.
