### ISSUE TITLE
Wei Gui

### ISSUE THREAD

**Issue by josephLeiferman** [dhuang12138/CS2820#13]
Close this ticket once getRouteWithShelf() has been implemented with the robot. 

This method should be called only when a robot has picked up a shelf. Otherwise call getRoute(). As well as for this to work you need to update shelf location as soon as a collision occurs. This is so when you call getRouteWithShelf() the floor knows the most current spot of any shelves that it needs to avoid.

**Comment by di-huang** [comment]
I think I can work getRoute algorithm with you since I designed and wrote almost everything (including Robot) in the code of the final production (not production_unitTesting).

**Comment by josephLeiferman** [comment]
Huh? I already did both getRoute() and getRouteWithShelf() they just need to be used with the robot  correctly.

**Comment by di-huang** [comment]
Now, I can't get contact with Wei Gun, maybe he's busy with other stuffs.

**Comment by weigui** [comment]
I'm now looking at it

**Comment by dhuang12138** [comment]
为什么不回我微信啊

**Comment by weigui** [comment]
手机没电了

**Comment by di-huang** [comment]
why not reply me on WeChat?   xD

**Comment by di-huang** [comment]
SO just charge your phone. We meet tonight??

**Comment by josephLeiferman** [comment]
我可以懂你。

**Comment by weigui** [comment]
XDDDDDD

**Comment by di-huang** [comment]
@josephLeiferman  I will try to make it compatible asap

**Comment by di-huang** [comment]
I just got up 30 mins ago  xD  (too tired)

**Comment by josephLeiferman** [comment]
Okay, sweet if you need help or have any question my phone number is in one of the issues.

**Comment by di-huang** [comment]
Just change getRoute() to getRouteWithShelf at two cases: headingToShelf and HeadingToPicker

**Comment by di-huang** [comment]
@josephLeiferman  it works without that BUG now, but the new route would be kind of weird since it.. xD (see by your own)

**Comment by weigui** [comment]
@josephLeiferman 
Although the route is a little bit strange... It still works very well.
Thanks for your effort!
I'm closing this issue.

**Comment by josephLeiferman** [comment]
Yes the route might seem weird, I just changed the code so that if it finds that their is a shelf in its path it just goes the opposite direction then continues on..lol

**Comment by josephLeiferman** [comment]
Also I am just wondering, not saying we have to do this, but did we every try to do multiple robots?

**Comment by weigui** [comment]
Maybe we'll do it, maybe not

**Comment by di-huang** [comment]
@josephLeiferman we probably will not do multiple robots, because there's also only one robot simulated in professor's demo project. However, I think your finding-route-algorithm is able to handle the check-if-robot-collided problem since robot actually has a same attribute as shelf does (they both are entity and can not be passed through directly).

**Comment by josephLeiferman** [comment]
Okay not a problem, I was just curious I didn't think we would have time to anyways.
