### ISSUE TITLE
Presentation Thursday

### ISSUE THREAD

**Issue by ghost** [dhuang12138/CS2820#16]
@NickEBarnes  We decided that we would each be describing our own portion's contribution to the demo. I know not all of us had a direct hand in production but I'm sure if you study the code Di Huang wrote you can find something to talk about, or you can also talk about about what your code does in the separate repo you made. I'm pretty sure the presentation tomorrow is not a big deal at all and people are going to be pretty wowed by the visualization that a few group members have been collaborating on, it looks really nice.

**Comment by NickEBarnes** [comment]
Okay, well I can speak on his belt if you want. Don't really see a point in talking about mine since it doesn't have much to do with the demo. I will plan on giving a brief run through of how the demo belt works, is that cool with you Di?
