### ISSUE TITLE
We'd better generate java doc files as help documents.

### ISSUE THREAD

**Issue by di-huang** [dhuang12138/CS2820#18]

**Comment by josephLeiferman** [comment]
We code has the java doc tags so all someone needs to do is generate them. I don't think others peoples code does though, if you guys need examples you can see Floor.java. Once everyone has the tags its as simple as hitting a button.

**Comment by josephLeiferman** [comment]
Just go to project tab then generate javadoc.. I had created them on an earlier build, but deleted them because just my code had the tags

**Comment by di-huang** [comment]
yea, its a easy work , just type some commands on terminal..
