### ISSUE TITLE
Good work Joseph

### ISSUE THREAD

**Issue by NickEBarnes** [dhuang12138/CS2820#2]
Everything looks good, thank you for taking the time to put it all together

**Comment by josephLeiferman** [comment]
Not a problem. I thought it would be easier for one person to move everything over than all of us trying to. I have free time tonight so I'll work on Production.java then.

**Comment by weigui** [comment]
Thank you Joseph :D

**Comment by di-huang** [comment]
@josephLeiferman Thx, it should be my work. However, our project doesn't run as desired for now, so I'll work on it during the break.
