### ISSUE TITLE
Shelves passing through other shelves

### ISSUE THREAD

**Issue by josephLeiferman** [dhuang12138/CS2820#9]
Hi just wanted to create this issue so as to communicate with Wei Gui who I believe is working on the robot. So what I'll will get done by tonight is create an additional getRouteWithShelve() that will be called when a robot has picked up a shelve so that doesn't all it to move through entities. I will not remove the other getRoute() because that one will be needed for a robot to get to a shelf in the first place, but once it has picked up a shelf it will call getRouteWithShelve() with a destination of to the picker, or other location. I hope you understand this, I will comment again on this issue when it is done so that you can implement it with your robot.

**Comment by weigui** [comment]
That's what I expected!
Robot should be able to pass through a shelf if it isn't carrying a shelf

**Comment by josephLeiferman** [comment]
Also one request the will help the implementation when a 'collision' occurs where robots with shelves are blocking each other could your implementation update the shelves location to the spots there currently stuck at. So when you call getroutewithalshelf() the floor knows where those shelves are at so that it can creat a path around each other.

**Comment by josephLeiferman** [comment]
I have fixed this problem now! When a robot has picked up a shelf and needs to return or bring to picked call the function getRouteWithShelf() instead of getRoute()
